language: perl
matrix:
  include:
    - perl: "5.24"
      dist: xenial
    - perl: "5.20"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.10"
      dist: trusty
env:
  - "HARNESS_OPTIONS=j9"
install:
  - "cpanm -n https://github.com/jhthorsen/json-validator/archive/master.tar.gz"
  - "cpanm -n https://github.com/jhthorsen/mojolicious-plugin-openapi/archive/master.tar.gz"
  - "cpanm -n Test::Pod Test::Pod::Coverage IO::Socket::SSL"
  - "cpanm -n --installdeps ."
notifications:
  email: false
